//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtauMobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUtauMobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外观与语言.
        /// </summary>
        internal static string AppearanceAndLanguage {
            get {
                return ResourceManager.GetString("AppearanceAndLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenUtau Mobile.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 走带自动翻页.
        /// </summary>
        internal static string AutomaticPageTurning {
            get {
                return ResourceManager.GetString("AutomaticPageTurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若打开，将在播放指针到达页面右侧时自动翻页.
        /// </summary>
        internal static string AutomaticPageTurningTooltip {
            get {
                return ResourceManager.GetString("AutomaticPageTurningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        internal static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一种 压缩包 编码方式，使得右侧文字显示正常.
        /// </summary>
        internal static string CompressionEncodingMethodPrompt {
            get {
                return ResourceManager.GetString("CompressionEncodingMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示歌手立绘.
        /// </summary>
        internal static string DisplaySingerPortrait {
            get {
                return ResourceManager.GetString("DisplaySingerPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开后，将在钢琴卷帘中显示歌手的立绘。.
        /// </summary>
        internal static string DisplaySingerPortraitTooltip {
            get {
                return ResourceManager.GetString("DisplaySingerPortraitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不渲染静音的轨道.
        /// </summary>
        internal static string DontRenderMutedTracks {
            get {
                return ResourceManager.GetString("DontRenderMutedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染时跳过静音的轨道。.
        /// </summary>
        internal static string DontRenderMutedTracksTooltip {
            get {
                return ResourceManager.GetString("DontRenderMutedTracksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑与行为.
        /// </summary>
        internal static string EditAndBehaviour {
            get {
                return ResourceManager.GetString("EditAndBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出日志.
        /// </summary>
        internal static string ExportLog {
            get {
                return ResourceManager.GetString("ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件与存储.
        /// </summary>
        internal static string FileAndStorage {
            get {
                return ResourceManager.GetString("FileAndStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 去 GitHub 给项目提建议、贡献代码或者给个星标吧.
        /// </summary>
        internal static string GitHubSuggestionsText {
            get {
                return ResourceManager.GetString("GitHubSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局立绘透明度.
        /// </summary>
        internal static string GlobalPortraitTransparency {
            get {
                return ResourceManager.GetString("GlobalPortraitTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开该选项可覆盖所有歌手立绘透明度预设。.
        /// </summary>
        internal static string GlobalPortraitTransparencyTooltip {
            get {
                return ResourceManager.GetString("GlobalPortraitTransparencyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助与教程.
        /// </summary>
        internal static string HelpAndTutorial {
            get {
                return ResourceManager.GetString("HelpAndTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助 OpenUtau Mobile 变得更好.
        /// </summary>
        internal static string HelpGetBetterText {
            get {
                return ResourceManager.GetString("HelpGetBetterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始安装.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装完成.
        /// </summary>
        internal static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装目录.
        /// </summary>
        internal static string InstallationDirectoryText {
            get {
                return ResourceManager.GetString("InstallationDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装路径：.
        /// </summary>
        internal static string InstallationPath {
            get {
                return ResourceManager.GetString("InstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装大小.
        /// </summary>
        internal static string InstallationSizeText {
            get {
                return ResourceManager.GetString("InstallationSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装信息摘要.
        /// </summary>
        internal static string InstallationSummary {
            get {
                return ResourceManager.GetString("InstallationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装中.
        /// </summary>
        internal static string InstallingText {
            get {
                return ResourceManager.GetString("InstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保持屏幕常亮.
        /// </summary>
        internal static string KeepScreenOn {
            get {
                return ResourceManager.GetString("KeepScreenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开后，将在编辑页面中保持屏幕常亮。.
        /// </summary>
        internal static string KeepScreenOnTooltip {
            get {
                return ResourceManager.GetString("KeepScreenOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 德语.
        /// </summary>
        internal static string Languages_de {
            get {
                return ResourceManager.GetString("Languages_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英语.
        /// </summary>
        internal static string Languages_en {
            get {
                return ResourceManager.GetString("Languages_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西班牙语.
        /// </summary>
        internal static string Languages_es {
            get {
                return ResourceManager.GetString("Languages_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法语.
        /// </summary>
        internal static string Languages_fr {
            get {
                return ResourceManager.GetString("Languages_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不翻译.
        /// </summary>
        internal static string Languages_invariant {
            get {
                return ResourceManager.GetString("Languages_invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意大利语.
        /// </summary>
        internal static string Languages_it {
            get {
                return ResourceManager.GetString("Languages_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日语.
        /// </summary>
        internal static string Languages_ja {
            get {
                return ResourceManager.GetString("Languages_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 韩语.
        /// </summary>
        internal static string Languages_ko {
            get {
                return ResourceManager.GetString("Languages_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波兰语.
        /// </summary>
        internal static string Languages_pl {
            get {
                return ResourceManager.GetString("Languages_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 葡萄牙语.
        /// </summary>
        internal static string Languages_pt {
            get {
                return ResourceManager.GetString("Languages_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 俄语.
        /// </summary>
        internal static string Languages_ru {
            get {
                return ResourceManager.GetString("Languages_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泰语.
        /// </summary>
        internal static string Languages_th {
            get {
                return ResourceManager.GetString("Languages_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 越南语.
        /// </summary>
        internal static string Languages_vi {
            get {
                return ResourceManager.GetString("Languages_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        internal static string Languages_zh {
            get {
                return ResourceManager.GetString("Languages_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粤语.
        /// </summary>
        internal static string Languages_zh_yue {
            get {
                return ResourceManager.GetString("Languages_zh_yue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这里还没有打开过的工程.
        /// </summary>
        internal static string NoProjectsOpened {
            get {
                return ResourceManager.GetString("NoProjectsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没有歌手，点击“+”添加！.
        /// </summary>
        internal static string NoSingerPrompt {
            get {
                return ResourceManager.GetString("NoSingerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击钢琴键时.
        /// </summary>
        internal static string OnPianoClick {
            get {
                return ResourceManager.GetString("OnPianoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置点击钢琴卷帘左侧琴键的行为.
        /// </summary>
        internal static string OnPianoClickTooltip {
            get {
                return ResourceManager.GetString("OnPianoClickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenUtau 内核版本.
        /// </summary>
        internal static string OpenUtauCoreVersion {
            get {
                return ResourceManager.GetString("OpenUtauCoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenUtau Mobile 版本.
        /// </summary>
        internal static string OpenUtauMobileVersion {
            get {
                return ResourceManager.GetString("OpenUtauMobileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出设备.
        /// </summary>
        internal static string OutputDevice {
            get {
                return ResourceManager.GetString("OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android只能看不能改.
        /// </summary>
        internal static string OutputDeviceTooltip {
            get {
                return ResourceManager.GetString("OutputDeviceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音高线显示精度.
        /// </summary>
        internal static string PitchDisplayPrecision {
            get {
                return ResourceManager.GetString("PitchDisplayPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更高的精度更能准确刻画实际音高，但可能导致性能问题。.
        /// </summary>
        internal static string PitchDisplayPrecisionTooltip {
            get {
                return ResourceManager.GetString("PitchDisplayPrecisionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放刷新率.
        /// </summary>
        internal static string PlaybackRefreshRate {
            get {
                return ResourceManager.GetString("PlaybackRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置更新播放指针的频率，1 ~ 60 FPS。请根据设备性能调整。过大的刷新率可能导致卡顿。更改此项设置后，重新打开编辑页面生效。.
        /// </summary>
        internal static string PlaybackRefreshRateTooltip {
            get {
                return ResourceManager.GetString("PlaybackRefreshRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预渲染.
        /// </summary>
        internal static string PreRender {
            get {
                return ResourceManager.GetString("PreRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在回放前后台预渲染音频。.
        /// </summary>
        internal static string PreRenderTooltip {
            get {
                return ResourceManager.GetString("PreRenderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近.
        /// </summary>
        internal static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近打开.
        /// </summary>
        internal static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染与性能.
        /// </summary>
        internal static string RenderAndPerformance {
            get {
                return ResourceManager.GetString("RenderAndPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手信息缺失，请选择歌手类型：.
        /// </summary>
        internal static string SingerInformationMissing {
            get {
                return ResourceManager.GetString("SingerInformationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手管理.
        /// </summary>
        internal static string SingerManage {
            get {
                return ResourceManager.GetString("SingerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手名称.
        /// </summary>
        internal static string SingerNameText {
            get {
                return ResourceManager.GetString("SingerNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手.
        /// </summary>
        internal static string Singers {
            get {
                return ResourceManager.GetString("Singers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手安装向导.
        /// </summary>
        internal static string SingerSetupWizard {
            get {
                return ResourceManager.GetString("SingerSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手类型.
        /// </summary>
        internal static string SingerTypeText {
            get {
                return ResourceManager.GetString("SingerTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        internal static string StringHomePage {
            get {
                return ResourceManager.GetString("StringHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再次按下返回键退出 OpenUtau Mobile.
        /// </summary>
        internal static string StringPressBackAgainToExit {
            get {
                return ResourceManager.GetString("StringPressBackAgainToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一种 文本 编码方式，使得右侧文字显示正常.
        /// </summary>
        internal static string TextEncodingMethodPrompt {
            get {
                return ResourceManager.GetString("TextEncodingMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色或浅色主题.
        /// </summary>
        internal static string ThemeTooltip {
            get {
                return ResourceManager.GetString("ThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透明度.
        /// </summary>
        internal static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本：.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 即将安装Vogen歌手.
        /// </summary>
        internal static string VogenSingerInstalledSoon {
            get {
                return ResourceManager.GetString("VogenSingerInstalledSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vogen歌手安装向导.
        /// </summary>
        internal static string VogenSingerSetupWizard {
            get {
                return ResourceManager.GetString("VogenSingerSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站：.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择正确的文件 *{0}.
        /// </summary>
        internal static string WrongFileTypeToast {
            get {
                return ResourceManager.GetString("WrongFileTypeToast", resourceCulture);
            }
        }
    }
}
