//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtauMobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUtauMobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 中止 的本地化字符串。
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AI正在推理... 的本地化字符串。
        /// </summary>
        internal static string AIProcessing {
            get {
                return ResourceManager.GetString("AIProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观与语言 的本地化字符串。
        /// </summary>
        internal static string AppearanceAndLanguage {
            get {
                return ResourceManager.GetString("AppearanceAndLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenUtau Mobile 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 走带自动翻页 的本地化字符串。
        /// </summary>
        internal static string AutomaticPageTurning {
            get {
                return ResourceManager.GetString("AutomaticPageTurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 若打开，将在播放指针到达页面右侧时自动翻页 的本地化字符串。
        /// </summary>
        internal static string AutomaticPageTurningTooltip {
            get {
                return ResourceManager.GetString("AutomaticPageTurningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一种 压缩包 编码方式，使得右侧文字显示正常 的本地化字符串。
        /// </summary>
        internal static string CompressionEncodingMethodPrompt {
            get {
                return ResourceManager.GetString("CompressionEncodingMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再次操作以取消歌手安装 的本地化字符串。
        /// </summary>
        internal static string ConfirmCancelSingerInstallToast {
            get {
                return ResourceManager.GetString("ConfirmCancelSingerInstallToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示歌手立绘 的本地化字符串。
        /// </summary>
        internal static string DisplaySingerPortrait {
            get {
                return ResourceManager.GetString("DisplaySingerPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开后，将在钢琴卷帘中显示歌手的立绘。 的本地化字符串。
        /// </summary>
        internal static string DisplaySingerPortraitTooltip {
            get {
                return ResourceManager.GetString("DisplaySingerPortraitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不渲染静音的轨道 的本地化字符串。
        /// </summary>
        internal static string DontRenderMutedTracks {
            get {
                return ResourceManager.GetString("DontRenderMutedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染时跳过静音的轨道。 的本地化字符串。
        /// </summary>
        internal static string DontRenderMutedTracksTooltip {
            get {
                return ResourceManager.GetString("DontRenderMutedTracksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑与行为 的本地化字符串。
        /// </summary>
        internal static string EditAndBehaviour {
            get {
                return ResourceManager.GetString("EditAndBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出日志 的本地化字符串。
        /// </summary>
        internal static string ExportLog {
            get {
                return ResourceManager.GetString("ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件与存储 的本地化字符串。
        /// </summary>
        internal static string FileAndStorage {
            get {
                return ResourceManager.GetString("FileAndStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到指定文件 的本地化字符串。
        /// </summary>
        internal static string FileNotFoundToast {
            get {
                return ResourceManager.GetString("FileNotFoundToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去 GitHub 给项目提建议、贡献代码或者给个星标吧 的本地化字符串。
        /// </summary>
        internal static string GitHubSuggestionsText {
            get {
                return ResourceManager.GetString("GitHubSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局立绘透明度 的本地化字符串。
        /// </summary>
        internal static string GlobalPortraitTransparency {
            get {
                return ResourceManager.GetString("GlobalPortraitTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开该选项可覆盖所有歌手立绘透明度预设。 的本地化字符串。
        /// </summary>
        internal static string GlobalPortraitTransparencyTooltip {
            get {
                return ResourceManager.GetString("GlobalPortraitTransparencyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助与教程 的本地化字符串。
        /// </summary>
        internal static string HelpAndTutorial {
            get {
                return ResourceManager.GetString("HelpAndTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 OpenUtau Mobile 变得更好 的本地化字符串。
        /// </summary>
        internal static string HelpGetBetterText {
            get {
                return ResourceManager.GetString("HelpGetBetterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的工程文件 的本地化字符串。
        /// </summary>
        internal static string IncorrectProjectFileToast {
            get {
                return ResourceManager.GetString("IncorrectProjectFileToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始安装 的本地化字符串。
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装已取消！ 的本地化字符串。
        /// </summary>
        internal static string InstallationCancelledToast {
            get {
                return ResourceManager.GetString("InstallationCancelledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装完成 的本地化字符串。
        /// </summary>
        internal static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装目录 的本地化字符串。
        /// </summary>
        internal static string InstallationDirectoryText {
            get {
                return ResourceManager.GetString("InstallationDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装路径： 的本地化字符串。
        /// </summary>
        internal static string InstallationPath {
            get {
                return ResourceManager.GetString("InstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装大小 的本地化字符串。
        /// </summary>
        internal static string InstallationSizeText {
            get {
                return ResourceManager.GetString("InstallationSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装信息摘要 的本地化字符串。
        /// </summary>
        internal static string InstallationSummary {
            get {
                return ResourceManager.GetString("InstallationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装中 的本地化字符串。
        /// </summary>
        internal static string InstallingText {
            get {
                return ResourceManager.GetString("InstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保持屏幕常亮 的本地化字符串。
        /// </summary>
        internal static string KeepScreenOn {
            get {
                return ResourceManager.GetString("KeepScreenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开后，将在编辑页面中保持屏幕常亮。 的本地化字符串。
        /// </summary>
        internal static string KeepScreenOnTooltip {
            get {
                return ResourceManager.GetString("KeepScreenOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 德语 的本地化字符串。
        /// </summary>
        internal static string Languages_de {
            get {
                return ResourceManager.GetString("Languages_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string Languages_en {
            get {
                return ResourceManager.GetString("Languages_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西班牙语 的本地化字符串。
        /// </summary>
        internal static string Languages_es {
            get {
                return ResourceManager.GetString("Languages_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法语 的本地化字符串。
        /// </summary>
        internal static string Languages_fr {
            get {
                return ResourceManager.GetString("Languages_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不翻译 的本地化字符串。
        /// </summary>
        internal static string Languages_invariant {
            get {
                return ResourceManager.GetString("Languages_invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意大利语 的本地化字符串。
        /// </summary>
        internal static string Languages_it {
            get {
                return ResourceManager.GetString("Languages_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日语 的本地化字符串。
        /// </summary>
        internal static string Languages_ja {
            get {
                return ResourceManager.GetString("Languages_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韩语 的本地化字符串。
        /// </summary>
        internal static string Languages_ko {
            get {
                return ResourceManager.GetString("Languages_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波兰语 的本地化字符串。
        /// </summary>
        internal static string Languages_pl {
            get {
                return ResourceManager.GetString("Languages_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 葡萄牙语 的本地化字符串。
        /// </summary>
        internal static string Languages_pt {
            get {
                return ResourceManager.GetString("Languages_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俄语 的本地化字符串。
        /// </summary>
        internal static string Languages_ru {
            get {
                return ResourceManager.GetString("Languages_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泰语 的本地化字符串。
        /// </summary>
        internal static string Languages_th {
            get {
                return ResourceManager.GetString("Languages_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 越南语 的本地化字符串。
        /// </summary>
        internal static string Languages_vi {
            get {
                return ResourceManager.GetString("Languages_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string Languages_zh {
            get {
                return ResourceManager.GetString("Languages_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粤语 的本地化字符串。
        /// </summary>
        internal static string Languages_zh_yue {
            get {
                return ResourceManager.GetString("Languages_zh_yue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载音高渲染结果 的本地化字符串。
        /// </summary>
        internal static string LoadPitchRenderingResult {
            get {
                return ResourceManager.GetString("LoadPitchRenderingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取渲染器推荐音高曲线。但渲染结果会覆盖已有音高数据，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string LoadPitchRenderingResultPrompt {
            get {
                return ResourceManager.GetString("LoadPitchRenderingResultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这里还没有打开过的工程 的本地化字符串。
        /// </summary>
        internal static string NoProjectsOpened {
            get {
                return ResourceManager.GetString("NoProjectsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有歌手，点击“+”添加！ 的本地化字符串。
        /// </summary>
        internal static string NoSingerPrompt {
            get {
                return ResourceManager.GetString("NoSingerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击钢琴键时 的本地化字符串。
        /// </summary>
        internal static string OnPianoClick {
            get {
                return ResourceManager.GetString("OnPianoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置点击钢琴卷帘左侧琴键的行为 的本地化字符串。
        /// </summary>
        internal static string OnPianoClickTooltip {
            get {
                return ResourceManager.GetString("OnPianoClickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenUtau 内核版本 的本地化字符串。
        /// </summary>
        internal static string OpenUtauCoreVersion {
            get {
                return ResourceManager.GetString("OpenUtauCoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenUtau Mobile 版本 的本地化字符串。
        /// </summary>
        internal static string OpenUtauMobileVersion {
            get {
                return ResourceManager.GetString("OpenUtauMobileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出设备 的本地化字符串。
        /// </summary>
        internal static string OutputDevice {
            get {
                return ResourceManager.GetString("OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Android只能看不能改 的本地化字符串。
        /// </summary>
        internal static string OutputDeviceTooltip {
            get {
                return ResourceManager.GetString("OutputDeviceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钢琴卷帘量化 的本地化字符串。
        /// </summary>
        internal static string PianoRollQuantization {
            get {
                return ResourceManager.GetString("PianoRollQuantization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音高线显示精度 的本地化字符串。
        /// </summary>
        internal static string PitchDisplayPrecision {
            get {
                return ResourceManager.GetString("PitchDisplayPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更高的精度更能准确刻画实际音高，但可能导致性能问题。 的本地化字符串。
        /// </summary>
        internal static string PitchDisplayPrecisionTooltip {
            get {
                return ResourceManager.GetString("PitchDisplayPrecisionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放刷新率 的本地化字符串。
        /// </summary>
        internal static string PlaybackRefreshRate {
            get {
                return ResourceManager.GetString("PlaybackRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置更新播放指针的频率，1 ~ 60 FPS。请根据设备性能调整。过大的刷新率可能导致卡顿。更改此项设置后，重新打开编辑页面生效。 的本地化字符串。
        /// </summary>
        internal static string PlaybackRefreshRateTooltip {
            get {
                return ResourceManager.GetString("PlaybackRefreshRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预渲染 的本地化字符串。
        /// </summary>
        internal static string PreRender {
            get {
                return ResourceManager.GetString("PreRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在回放前后台预渲染音频。 的本地化字符串。
        /// </summary>
        internal static string PreRenderTooltip {
            get {
                return ResourceManager.GetString("PreRenderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近 的本地化字符串。
        /// </summary>
        internal static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近打开 的本地化字符串。
        /// </summary>
        internal static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载歌手 的本地化字符串。
        /// </summary>
        internal static string RemoveSinger {
            get {
                return ResourceManager.GetString("RemoveSinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载歌手 {0} 失败 的本地化字符串。
        /// </summary>
        internal static string RemoveSingerFailureToast {
            get {
                return ResourceManager.GetString("RemoveSingerFailureToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要卸载歌手 {0} 吗？ 的本地化字符串。
        /// </summary>
        internal static string RemoveSingerPrompt {
            get {
                return ResourceManager.GetString("RemoveSingerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功卸载歌手 {0} 的本地化字符串。
        /// </summary>
        internal static string RemoveSingerSuccessToast {
            get {
                return ResourceManager.GetString("RemoveSingerSuccessToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在卸载歌手 {0}... 的本地化字符串。
        /// </summary>
        internal static string RemovingSingerToast {
            get {
                return ResourceManager.GetString("RemovingSingerToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名分片 的本地化字符串。
        /// </summary>
        internal static string RenamePart {
            get {
                return ResourceManager.GetString("RenamePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名音轨 的本地化字符串。
        /// </summary>
        internal static string RenameTrack {
            get {
                return ResourceManager.GetString("RenameTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染与性能 的本地化字符串。
        /// </summary>
        internal static string RenderAndPerformance {
            get {
                return ResourceManager.GetString("RenderAndPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存 的本地化字符串。
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置已保存 的本地化字符串。
        /// </summary>
        internal static string SettingsSavedToast {
            get {
                return ResourceManager.GetString("SettingsSavedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置时出现错误 的本地化字符串。
        /// </summary>
        internal static string SettingsSaveErrorToast {
            get {
                return ResourceManager.GetString("SettingsSaveErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌手信息缺失，请选择歌手类型： 的本地化字符串。
        /// </summary>
        internal static string SingerInformationMissing {
            get {
                return ResourceManager.GetString("SingerInformationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌手管理 的本地化字符串。
        /// </summary>
        internal static string SingerManage {
            get {
                return ResourceManager.GetString("SingerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌手名称 的本地化字符串。
        /// </summary>
        internal static string SingerNameText {
            get {
                return ResourceManager.GetString("SingerNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌手 的本地化字符串。
        /// </summary>
        internal static string Singers {
            get {
                return ResourceManager.GetString("Singers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌手安装向导 的本地化字符串。
        /// </summary>
        internal static string SingerSetupWizard {
            get {
                return ResourceManager.GetString("SingerSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌手类型 的本地化字符串。
        /// </summary>
        internal static string SingerTypeText {
            get {
                return ResourceManager.GetString("SingerTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string StringHomePage {
            get {
                return ResourceManager.GetString("StringHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再次按下返回键退出 OpenUtau Mobile 的本地化字符串。
        /// </summary>
        internal static string StringPressBackAgainToExit {
            get {
                return ResourceManager.GetString("StringPressBackAgainToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一种 文本 编码方式，使得右侧文字显示正常 的本地化字符串。
        /// </summary>
        internal static string TextEncodingMethodPrompt {
            get {
                return ResourceManager.GetString("TextEncodingMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色或浅色主题 的本地化字符串。
        /// </summary>
        internal static string ThemeTooltip {
            get {
                return ResourceManager.GetString("ThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度 的本地化字符串。
        /// </summary>
        internal static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本： 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即将安装Vogen歌手 的本地化字符串。
        /// </summary>
        internal static string VogenSingerInstalledSoon {
            get {
                return ResourceManager.GetString("VogenSingerInstalledSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vogen歌手安装向导 的本地化字符串。
        /// </summary>
        internal static string VogenSingerSetupWizard {
            get {
                return ResourceManager.GetString("VogenSingerSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站： 的本地化字符串。
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在导出 的本地化字符串。
        /// </summary>
        internal static string WorkTitleExport {
            get {
                return ResourceManager.GetString("WorkTitleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载项目，请勿操作 的本地化字符串。
        /// </summary>
        internal static string WorkTitleLoadingProject {
            get {
                return ResourceManager.GetString("WorkTitleLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作中 的本地化字符串。
        /// </summary>
        internal static string WorkTitleOther {
            get {
                return ResourceManager.GetString("WorkTitleOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在音素化 的本地化字符串。
        /// </summary>
        internal static string WorkTitlePhonemize {
            get {
                return ResourceManager.GetString("WorkTitlePhonemize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在渲染音频波形 的本地化字符串。
        /// </summary>
        internal static string WorkTitleReadWave {
            get {
                return ResourceManager.GetString("WorkTitleReadWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在渲染 的本地化字符串。
        /// </summary>
        internal static string WorkTitleRender {
            get {
                return ResourceManager.GetString("WorkTitleRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在渲染音高 的本地化字符串。
        /// </summary>
        internal static string WorkTitleRenderPitch {
            get {
                return ResourceManager.GetString("WorkTitleRenderPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的文件 *{0} 的本地化字符串。
        /// </summary>
        internal static string WrongFileTypeToast {
            get {
                return ResourceManager.GetString("WrongFileTypeToast", resourceCulture);
            }
        }
    }
}
