//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtauMobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUtauMobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中止.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI正在推理....
        /// </summary>
        internal static string AIProcessing {
            get {
                return ResourceManager.GetString("AIProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外观与语言.
        /// </summary>
        internal static string AppearanceAndLanguage {
            get {
                return ResourceManager.GetString("AppearanceAndLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenUtau Mobile.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenUtau Mobile 运行时异常.
        /// </summary>
        internal static string AppRuntimeException {
            get {
                return ResourceManager.GetString("AppRuntimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在第.
        /// </summary>
        internal static string AtBarText {
            get {
                return ResourceManager.GetString("AtBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作中.
        /// </summary>
        internal static string AtWork {
            get {
                return ResourceManager.GetString("AtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出音频选项.
        /// </summary>
        internal static string AudioExportOptions {
            get {
                return ResourceManager.GetString("AudioExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 走带自动翻页.
        /// </summary>
        internal static string AutomaticPageTurning {
            get {
                return ResourceManager.GetString("AutomaticPageTurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若打开，将在播放指针到达页面右侧时自动翻页.
        /// </summary>
        internal static string AutomaticPageTurningTooltip {
            get {
                return ResourceManager.GetString("AutomaticPageTurningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助工具.
        /// </summary>
        internal static string AuxiliaryTools {
            get {
                return ResourceManager.GetString("AuxiliaryTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        internal static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小节.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小节不能为负.
        /// </summary>
        internal static string BarNegativeToast {
            get {
                return ResourceManager.GetString("BarNegativeToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每小节拍数.
        /// </summary>
        internal static string BeatsPerMeasure {
            get {
                return ResourceManager.GetString("BeatsPerMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位深.
        /// </summary>
        internal static string BitDepth {
            get {
                return ResourceManager.GetString("BitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改变轨道颜色.
        /// </summary>
        internal static string ChangeTrackColor {
            get {
                return ResourceManager.GetString("ChangeTrackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭项目.
        /// </summary>
        internal static string CloseProject {
            get {
                return ResourceManager.GetString("CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一种 压缩包 编码方式，使得右侧文字显示正常.
        /// </summary>
        internal static string CompressionEncodingMethodPrompt {
            get {
                return ResourceManager.GetString("CompressionEncodingMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再次操作以取消歌手安装.
        /// </summary>
        internal static string ConfirmCancelSingerInstallToast {
            get {
                return ResourceManager.GetString("ConfirmCancelSingerInstallToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已复制到剪贴板.
        /// </summary>
        internal static string CopiedToClipboardToast {
            get {
                return ResourceManager.GetString("CopiedToClipboardToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制错误信息.
        /// </summary>
        internal static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 曲速测定.
        /// </summary>
        internal static string DetectTempo {
            get {
                return ResourceManager.GetString("DetectTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示歌手立绘.
        /// </summary>
        internal static string DisplaySingerPortrait {
            get {
                return ResourceManager.GetString("DisplaySingerPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开后，将在钢琴卷帘中显示歌手的立绘。.
        /// </summary>
        internal static string DisplaySingerPortraitTooltip {
            get {
                return ResourceManager.GetString("DisplaySingerPortraitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不渲染静音的轨道.
        /// </summary>
        internal static string DontRenderMutedTracks {
            get {
                return ResourceManager.GetString("DontRenderMutedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染时跳过静音的轨道。.
        /// </summary>
        internal static string DontRenderMutedTracksTooltip {
            get {
                return ResourceManager.GetString("DontRenderMutedTracksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不保存.
        /// </summary>
        internal static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 干声转换.
        /// </summary>
        internal static string DryWetConversion {
            get {
                return ResourceManager.GetString("DryWetConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑与行为.
        /// </summary>
        internal static string EditAndBehaviour {
            get {
                return ResourceManager.GetString("EditAndBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑歌词.
        /// </summary>
        internal static string EditLyrics {
            get {
                return ResourceManager.GetString("EditLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入有效的数字.
        /// </summary>
        internal static string EnterValidNumberToast {
            get {
                return ResourceManager.GetString("EnterValidNumberToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误：{0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开项目文件，可能格式不受支持或文件已损坏。.
        /// </summary>
        internal static string ErrorFailLoadProject {
            get {
                return ResourceManager.GetString("ErrorFailLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误信息.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenUtau后端初始化失败.
        /// </summary>
        internal static string ErrorOpenUtauBackendInitializationFailed {
            get {
                return ResourceManager.GetString("ErrorOpenUtauBackendInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很抱歉， OpenUtau Mobile 捕获到了异常，部分功能可能无法正常使用。
        ///建议您将以下错误信息复制并反馈给开发者，并重启应用程序。
        ///
        ///{0}
        ///
        ///异常详情：
        ///{1}.
        /// </summary>
        internal static string ErrorPopupTemplate {
            get {
                return ResourceManager.GetString("ErrorPopupTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出音频.
        /// </summary>
        internal static string ExportAudio {
            get {
                return ResourceManager.GetString("ExportAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出日志.
        /// </summary>
        internal static string ExportLog {
            get {
                return ResourceManager.GetString("ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出工程.
        /// </summary>
        internal static string ExportProject {
            get {
                return ResourceManager.GetString("ExportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件与存储.
        /// </summary>
        internal static string FileAndStorage {
            get {
                return ResourceManager.GetString("FileAndStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到指定文件.
        /// </summary>
        internal static string FileNotFoundToast {
            get {
                return ResourceManager.GetString("FileNotFoundToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 去 GitHub 给项目提建议、贡献代码或者给个星标吧.
        /// </summary>
        internal static string GitHubSuggestionsText {
            get {
                return ResourceManager.GetString("GitHubSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局立绘透明度.
        /// </summary>
        internal static string GlobalPortraitTransparency {
            get {
                return ResourceManager.GetString("GlobalPortraitTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开该选项可覆盖所有歌手立绘透明度预设。.
        /// </summary>
        internal static string GlobalPortraitTransparencyTooltip {
            get {
                return ResourceManager.GetString("GlobalPortraitTransparencyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助与教程.
        /// </summary>
        internal static string HelpAndTutorial {
            get {
                return ResourceManager.GetString("HelpAndTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助 OpenUtau Mobile 变得更好.
        /// </summary>
        internal static string HelpGetBetterText {
            get {
                return ResourceManager.GetString("HelpGetBetterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入音频.
        /// </summary>
        internal static string ImportAudio {
            get {
                return ResourceManager.GetString("ImportAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入MIDI.
        /// </summary>
        internal static string ImportMidi {
            get {
                return ResourceManager.GetString("ImportMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入轨道.
        /// </summary>
        internal static string ImportTrack {
            get {
                return ResourceManager.GetString("ImportTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择正确的工程文件.
        /// </summary>
        internal static string IncorrectProjectFileToast {
            get {
                return ResourceManager.GetString("IncorrectProjectFileToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化完毕！.
        /// </summary>
        internal static string InitializationComplete {
            get {
                return ResourceManager.GetString("InitializationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化DocManager.
        /// </summary>
        internal static string InitializingDocManager {
            get {
                return ResourceManager.GetString("InitializingDocManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化语言本地化.
        /// </summary>
        internal static string InitializingLanguageLocalization {
            get {
                return ResourceManager.GetString("InitializingLanguageLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化对象提供器.
        /// </summary>
        internal static string InitializingObjectProvider {
            get {
                return ResourceManager.GetString("InitializingObjectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化钢琴卷帘.
        /// </summary>
        internal static string InitializingPianoRoll {
            get {
                return ResourceManager.GetString("InitializingPianoRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化PlaybackManager.
        /// </summary>
        internal static string InitializingPlaybackManager {
            get {
                return ResourceManager.GetString("InitializingPlaybackManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化SingerManager.
        /// </summary>
        internal static string InitializingSingerManager {
            get {
                return ResourceManager.GetString("InitializingSingerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化ToolsManager.
        /// </summary>
        internal static string InitializingToolsManager {
            get {
                return ResourceManager.GetString("InitializingToolsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入节拍标记.
        /// </summary>
        internal static string InsertSignatureMarker {
            get {
                return ResourceManager.GetString("InsertSignatureMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入曲速标记.
        /// </summary>
        internal static string InsertTempoMarker {
            get {
                return ResourceManager.GetString("InsertTempoMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入曲速或节拍标记.
        /// </summary>
        internal static string InsertTempoSignatureMarker {
            get {
                return ResourceManager.GetString("InsertTempoSignatureMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始安装.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装已取消！.
        /// </summary>
        internal static string InstallationCancelledToast {
            get {
                return ResourceManager.GetString("InstallationCancelledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装完成.
        /// </summary>
        internal static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装目录.
        /// </summary>
        internal static string InstallationDirectoryText {
            get {
                return ResourceManager.GetString("InstallationDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装路径：.
        /// </summary>
        internal static string InstallationPath {
            get {
                return ResourceManager.GetString("InstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装大小.
        /// </summary>
        internal static string InstallationSizeText {
            get {
                return ResourceManager.GetString("InstallationSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装信息摘要.
        /// </summary>
        internal static string InstallationSummary {
            get {
                return ResourceManager.GetString("InstallationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装中.
        /// </summary>
        internal static string InstallingText {
            get {
                return ResourceManager.GetString("InstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每小节拍数不能小于等于0.
        /// </summary>
        internal static string InvalidBeatsPerMeasureToast {
            get {
                return ResourceManager.GetString("InvalidBeatsPerMeasureToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM不能小于等于0.
        /// </summary>
        internal static string InvalidBPMToast {
            get {
                return ResourceManager.GetString("InvalidBPMToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以几分音符为一拍不能小于等于0.
        /// </summary>
        internal static string InvalidNotesPerBeatToast {
            get {
                return ResourceManager.GetString("InvalidNotesPerBeatToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保持屏幕常亮.
        /// </summary>
        internal static string KeepScreenOn {
            get {
                return ResourceManager.GetString("KeepScreenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开后，将在编辑页面中保持屏幕常亮。.
        /// </summary>
        internal static string KeepScreenOnTooltip {
            get {
                return ResourceManager.GetString("KeepScreenOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 德语.
        /// </summary>
        internal static string Languages_de {
            get {
                return ResourceManager.GetString("Languages_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英语.
        /// </summary>
        internal static string Languages_en {
            get {
                return ResourceManager.GetString("Languages_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西班牙语.
        /// </summary>
        internal static string Languages_es {
            get {
                return ResourceManager.GetString("Languages_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法语.
        /// </summary>
        internal static string Languages_fr {
            get {
                return ResourceManager.GetString("Languages_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不翻译.
        /// </summary>
        internal static string Languages_invariant {
            get {
                return ResourceManager.GetString("Languages_invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意大利语.
        /// </summary>
        internal static string Languages_it {
            get {
                return ResourceManager.GetString("Languages_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日语.
        /// </summary>
        internal static string Languages_ja {
            get {
                return ResourceManager.GetString("Languages_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 韩语.
        /// </summary>
        internal static string Languages_ko {
            get {
                return ResourceManager.GetString("Languages_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波兰语.
        /// </summary>
        internal static string Languages_pl {
            get {
                return ResourceManager.GetString("Languages_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 葡萄牙语.
        /// </summary>
        internal static string Languages_pt {
            get {
                return ResourceManager.GetString("Languages_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 俄语.
        /// </summary>
        internal static string Languages_ru {
            get {
                return ResourceManager.GetString("Languages_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泰语.
        /// </summary>
        internal static string Languages_th {
            get {
                return ResourceManager.GetString("Languages_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 越南语.
        /// </summary>
        internal static string Languages_vi {
            get {
                return ResourceManager.GetString("Languages_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        internal static string Languages_zh {
            get {
                return ResourceManager.GetString("Languages_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粤语.
        /// </summary>
        internal static string Languages_zh_yue {
            get {
                return ResourceManager.GetString("Languages_zh_yue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载音高渲染结果.
        /// </summary>
        internal static string LoadPitchRenderingResult {
            get {
                return ResourceManager.GetString("LoadPitchRenderingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取渲染器推荐音高曲线。但渲染结果会覆盖已有音高数据，是否继续？.
        /// </summary>
        internal static string LoadPitchRenderingResultPrompt {
            get {
                return ResourceManager.GetString("LoadPitchRenderingResultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表情管理.
        /// </summary>
        internal static string ManageExpressions {
            get {
                return ResourceManager.GetString("ManageExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小节标记节拍为.
        /// </summary>
        internal static string MarkBeatsAs {
            get {
                return ResourceManager.GetString("MarkBeatsAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩混.
        /// </summary>
        internal static string MixDown {
            get {
                return ResourceManager.GetString("MixDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 混音模式.
        /// </summary>
        internal static string MixingMode {
            get {
                return ResourceManager.GetString("MixingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新文件.
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新分片.
        /// </summary>
        internal static string NewPart {
            get {
                return ResourceManager.GetString("NewPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新轨道.
        /// </summary>
        internal static string NewTrack {
            get {
                return ResourceManager.GetString("NewTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一个.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有可用的颜色.
        /// </summary>
        internal static string NoColorsAvailable {
            get {
                return ResourceManager.GetString("NoColorsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这里还没有打开过的工程.
        /// </summary>
        internal static string NoProjectsOpened {
            get {
                return ResourceManager.GetString("NoProjectsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没有量化！请向社区报告问题。.
        /// </summary>
        internal static string NoQuantization {
            get {
                return ResourceManager.GetString("NoQuantization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没有可选的调！请向社区报告问题。.
        /// </summary>
        internal static string NoSelectableKeys {
            get {
                return ResourceManager.GetString("NoSelectableKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没有歌手，点击“+”添加！.
        /// </summary>
        internal static string NoSingerPrompt {
            get {
                return ResourceManager.GetString("NoSingerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没有歌手，请前往歌手管理页面添加！.
        /// </summary>
        internal static string NoSingersText {
            get {
                return ResourceManager.GetString("NoSingersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以几分音符为一拍.
        /// </summary>
        internal static string NotesPerBeat {
            get {
                return ResourceManager.GetString("NotesPerBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 个分片被选中.
        /// </summary>
        internal static string NPartsSelected {
            get {
                return ResourceManager.GetString("NPartsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击钢琴键时.
        /// </summary>
        internal static string OnPianoClick {
            get {
                return ResourceManager.GetString("OnPianoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钢琴采样TODO.
        /// </summary>
        internal static string OnPianoClickPianoSample {
            get {
                return ResourceManager.GetString("OnPianoClickPianoSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无声.
        /// </summary>
        internal static string OnPianoClickSilence {
            get {
                return ResourceManager.GetString("OnPianoClickSilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正弦波TODO.
        /// </summary>
        internal static string OnPianoClickSineWave {
            get {
                return ResourceManager.GetString("OnPianoClickSineWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置点击钢琴卷帘左侧琴键的行为.
        /// </summary>
        internal static string OnPianoClickTooltip {
            get {
                return ResourceManager.GetString("OnPianoClickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenUtau 内核版本.
        /// </summary>
        internal static string OpenUtauCoreVersion {
            get {
                return ResourceManager.GetString("OpenUtauCoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenUtau Mobile 版本.
        /// </summary>
        internal static string OpenUtauMobileVersion {
            get {
                return ResourceManager.GetString("OpenUtauMobileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出设备.
        /// </summary>
        internal static string OutputDevice {
            get {
                return ResourceManager.GetString("OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android只能看不能改.
        /// </summary>
        internal static string OutputDeviceTooltip {
            get {
                return ResourceManager.GetString("OutputDeviceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在音素化：.
        /// </summary>
        internal static string PhonemizingInProgress {
            get {
                return ResourceManager.GetString("PhonemizingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钢琴卷帘量化.
        /// </summary>
        internal static string PianoRollQuantization {
            get {
                return ResourceManager.GetString("PianoRollQuantization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音高线显示精度.
        /// </summary>
        internal static string PitchDisplayPrecision {
            get {
                return ResourceManager.GetString("PitchDisplayPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更高的精度更能准确刻画实际音高，但可能导致性能问题。.
        /// </summary>
        internal static string PitchDisplayPrecisionTooltip {
            get {
                return ResourceManager.GetString("PitchDisplayPrecisionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精细.
        /// </summary>
        internal static string PitchPrecisionFine {
            get {
                return ResourceManager.GetString("PitchPrecisionFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中等.
        /// </summary>
        internal static string PitchPrecisionMedium {
            get {
                return ResourceManager.GetString("PitchPrecisionMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原始.
        /// </summary>
        internal static string PitchPrecisionOriginal {
            get {
                return ResourceManager.GetString("PitchPrecisionOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粗略.
        /// </summary>
        internal static string PitchPrecisionRough {
            get {
                return ResourceManager.GetString("PitchPrecisionRough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放刷新率.
        /// </summary>
        internal static string PlaybackRefreshRate {
            get {
                return ResourceManager.GetString("PlaybackRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置更新播放指针的频率，1 ~ 60 FPS。请根据设备性能调整。过大的刷新率可能导致卡顿。更改此项设置后，重新打开编辑页面生效。.
        /// </summary>
        internal static string PlaybackRefreshRateTooltip {
            get {
                return ResourceManager.GetString("PlaybackRefreshRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置不能为负.
        /// </summary>
        internal static string PositionNegativeToast {
            get {
                return ResourceManager.GetString("PositionNegativeToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预渲染.
        /// </summary>
        internal static string PreRender {
            get {
                return ResourceManager.GetString("PreRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在回放前后台预渲染音频。.
        /// </summary>
        internal static string PreRenderTooltip {
            get {
                return ResourceManager.GetString("PreRenderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待波形处理....
        /// </summary>
        internal static string ProcessingWaveform {
            get {
                return ResourceManager.GetString("ProcessingWaveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波形处理被取消.
        /// </summary>
        internal static string ProcessingWaveformCancelled {
            get {
                return ResourceManager.GetString("ProcessingWaveformCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波形数据为空.
        /// </summary>
        internal static string ProcessingWaveformEmpty {
            get {
                return ResourceManager.GetString("ProcessingWaveformEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波形处理错误: {0}.
        /// </summary>
        internal static string ProcessingWaveformError {
            get {
                return ResourceManager.GetString("ProcessingWaveformError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波形处理未开始.
        /// </summary>
        internal static string ProcessingWaveformNotStarted {
            get {
                return ResourceManager.GetString("ProcessingWaveformNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进度：.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 量化.
        /// </summary>
        internal static string QuantizeText {
            get {
                return ResourceManager.GetString("QuantizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近.
        /// </summary>
        internal static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近打开.
        /// </summary>
        internal static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卸载歌手.
        /// </summary>
        internal static string RemoveSinger {
            get {
                return ResourceManager.GetString("RemoveSinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卸载歌手 {0} 失败.
        /// </summary>
        internal static string RemoveSingerFailureToast {
            get {
                return ResourceManager.GetString("RemoveSingerFailureToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要卸载歌手 {0} 吗？.
        /// </summary>
        internal static string RemoveSingerPrompt {
            get {
                return ResourceManager.GetString("RemoveSingerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功卸载歌手 {0}.
        /// </summary>
        internal static string RemoveSingerSuccessToast {
            get {
                return ResourceManager.GetString("RemoveSingerSuccessToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在卸载歌手 {0}....
        /// </summary>
        internal static string RemovingSingerToast {
            get {
                return ResourceManager.GetString("RemovingSingerToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名分片.
        /// </summary>
        internal static string RenamePart {
            get {
                return ResourceManager.GetString("RenamePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名音轨.
        /// </summary>
        internal static string RenameTrack {
            get {
                return ResourceManager.GetString("RenameTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染与性能.
        /// </summary>
        internal static string RenderAndPerformance {
            get {
                return ResourceManager.GetString("RenderAndPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波形文件渲染中....
        /// </summary>
        internal static string RenderingWaveformFile {
            get {
                return ResourceManager.GetString("RenderingWaveformFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启程序.
        /// </summary>
        internal static string RestartProgram {
            get {
                return ResourceManager.GetString("RestartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采样率.
        /// </summary>
        internal static string SampleRate {
            get {
                return ResourceManager.GetString("SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已保存.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存文件.
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工程另存为.
        /// </summary>
        internal static string SaveProjectAs {
            get {
                return ResourceManager.GetString("SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择文件.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择文件.
        /// </summary>
        internal static string SelectFileToast {
            get {
                return ResourceManager.GetString("SelectFileToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择音素器.
        /// </summary>
        internal static string SelectPhonemizer {
            get {
                return ResourceManager.GetString("SelectPhonemizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择文件保存位置.
        /// </summary>
        internal static string SelectSaveLocationToast {
            get {
                return ResourceManager.GetString("SelectSaveLocationToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择歌手.
        /// </summary>
        internal static string SelectSinger {
            get {
                return ResourceManager.GetString("SelectSinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伴奏分离.
        /// </summary>
        internal static string SeparateStems {
            get {
                return ResourceManager.GetString("SeparateStems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置节拍.
        /// </summary>
        internal static string SetBeat {
            get {
                return ResourceManager.GetString("SetBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置BPM.
        /// </summary>
        internal static string SetBPM {
            get {
                return ResourceManager.GetString("SetBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置调性.
        /// </summary>
        internal static string SetKey {
            get {
                return ResourceManager.GetString("SetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tick标记曲速为.
        /// </summary>
        internal static string SetTempoTickMarker {
            get {
                return ResourceManager.GetString("SetTempoTickMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置已保存.
        /// </summary>
        internal static string SettingsSavedToast {
            get {
                return ResourceManager.GetString("SettingsSavedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存设置时出现错误.
        /// </summary>
        internal static string SettingsSaveErrorToast {
            get {
                return ResourceManager.GetString("SettingsSaveErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... (已显示前 {0} 个条目).
        /// </summary>
        internal static string ShowingFirstNEntries {
            get {
                return ResourceManager.GetString("ShowingFirstNEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... (已显示前 {0} 个文本文件).
        /// </summary>
        internal static string ShowingFirstNTextFiles {
            get {
                return ResourceManager.GetString("ShowingFirstNTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手.
        /// </summary>
        internal static string Singer {
            get {
                return ResourceManager.GetString("Singer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手信息缺失，请选择歌手类型：.
        /// </summary>
        internal static string SingerInformationMissing {
            get {
                return ResourceManager.GetString("SingerInformationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手管理.
        /// </summary>
        internal static string SingerManage {
            get {
                return ResourceManager.GetString("SingerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手名称.
        /// </summary>
        internal static string SingerNameText {
            get {
                return ResourceManager.GetString("SingerNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手.
        /// </summary>
        internal static string Singers {
            get {
                return ResourceManager.GetString("Singers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手安装向导.
        /// </summary>
        internal static string SingerSetupWizard {
            get {
                return ResourceManager.GetString("SingerSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手类型.
        /// </summary>
        internal static string SingerTypeText {
            get {
                return ResourceManager.GetString("SingerTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存储权限被拒绝.
        /// </summary>
        internal static string StoragePermissionDeniedToast {
            get {
                return ResourceManager.GetString("StoragePermissionDeniedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        internal static string StringHomePage {
            get {
                return ResourceManager.GetString("StringHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再次按下返回键退出 OpenUtau Mobile.
        /// </summary>
        internal static string StringPressBackAgainToExit {
            get {
                return ResourceManager.GetString("StringPressBackAgainToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一种 文本 编码方式，使得右侧文字显示正常.
        /// </summary>
        internal static string TextEncodingMethodPrompt {
            get {
                return ResourceManager.GetString("TextEncodingMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色或浅色主题.
        /// </summary>
        internal static string ThemeTooltip {
            get {
                return ResourceManager.GetString("ThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tick时间单位.
        /// </summary>
        internal static string TickTime {
            get {
                return ResourceManager.GetString("TickTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透明度.
        /// </summary>
        internal static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知状态: {0}.
        /// </summary>
        internal static string UnknownStatus {
            get {
                return ResourceManager.GetString("UnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有尚未保存的更改，是否保存后退出？.
        /// </summary>
        internal static string UnsavedProjectChangesPrompt {
            get {
                return ResourceManager.GetString("UnsavedProjectChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本：.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分轨（仅歌声轨道）.
        /// </summary>
        internal static string VocalTrackOnly {
            get {
                return ResourceManager.GetString("VocalTrackOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 即将安装Vogen歌手.
        /// </summary>
        internal static string VogenSingerInstalledSoon {
            get {
                return ResourceManager.GetString("VogenSingerInstalledSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vogen歌手安装向导.
        /// </summary>
        internal static string VogenSingerSetupWizard {
            get {
                return ResourceManager.GetString("VogenSingerSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有权限访问该目录.
        /// </summary>
        internal static string WarningNoDirectoryPermission {
            get {
                return ResourceManager.GetString("WarningNoDirectoryPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该目录下没有子目录和符合条件的文件.
        /// </summary>
        internal static string WarningNoDirOrFilesMatchingCriteria {
            get {
                return ResourceManager.GetString("WarningNoDirOrFilesMatchingCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站：.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导出.
        /// </summary>
        internal static string WorkTitleExport {
            get {
                return ResourceManager.GetString("WorkTitleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载项目，请勿操作.
        /// </summary>
        internal static string WorkTitleLoadingProject {
            get {
                return ResourceManager.GetString("WorkTitleLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作中.
        /// </summary>
        internal static string WorkTitleOther {
            get {
                return ResourceManager.GetString("WorkTitleOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在音素化.
        /// </summary>
        internal static string WorkTitlePhonemize {
            get {
                return ResourceManager.GetString("WorkTitlePhonemize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在渲染音频波形.
        /// </summary>
        internal static string WorkTitleReadWave {
            get {
                return ResourceManager.GetString("WorkTitleReadWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在渲染.
        /// </summary>
        internal static string WorkTitleRender {
            get {
                return ResourceManager.GetString("WorkTitleRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在渲染音高.
        /// </summary>
        internal static string WorkTitleRenderPitch {
            get {
                return ResourceManager.GetString("WorkTitleRenderPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择正确的文件 *{0}.
        /// </summary>
        internal static string WrongFileTypeToast {
            get {
                return ResourceManager.GetString("WrongFileTypeToast", resourceCulture);
            }
        }
    }
}
