//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtau.Core.Vogen.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VogenRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VogenRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vogen.Data.VogenRes", typeof(VogenRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] f0_man {
            get {
                object obj = ResourceManager.GetObject("f0_man", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] f0_yue {
            get {
                object obj = ResourceManager.GetObject("f0_yue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] g2p_man {
            get {
                object obj = ResourceManager.GetObject("g2p_man", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] g2p_yue {
            get {
                object obj = ResourceManager.GetObject("g2p_yue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] po_man {
            get {
                object obj = ResourceManager.GetObject("po_man", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] po_yue {
            get {
                object obj = ResourceManager.GetObject("po_yue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ch,yue,yue-nn,yue-wz
        ///㐀,jau,jau,jau
        ///㐁,dou,du,dou
        ///㐂,cat,cat,cat
        ///㐃,zim,zim,zim
        ///㐄,kwaa,kwaa,kwaa
        ///㐅,ng,ng,ng
        ///㐆,ji,ji,ji
        ///㐇,gau,gau,gau
        ///㐈,jap,jap,jap
        ///㐉,ding,ding,ding
        ///㐊,si,si,si
        ///㐋,tou,tu,tou
        ///㐌,ji,taa,taa
        ///㐍,zaau,zaau,zaau
        ///㐎,man,man,man
        ///㐏,ng,ng,ng
        ///㐐,nou,nu,nou
        ///㐑,dung,dung,dung
        ///㐒,ziu,ziu,ziu
        ///㐓,ho,ho,ho
        ///㐔,hang,hang,hang
        ///㐕,jau,jau,jau
        ///㐖,kit,jit,jit
        ///㐗,lou,lu,lou
        ///㐘,mai,mai,mai
        ///㐙,dau,dau,dau
        ///㐚,ng,ng,ng
        ///㐛,jau,jau,jau
        ///㐜,sau,cau,cau
        ///㐝,keoi,kyu,kyu
        ///㐞,kei,ki,ki
        ///㐟,fei,fi,fi
        ///㐠,jyu,jyu,jyu
        ///㐡,no,no,no
        ///㐢,fau,fau,fau
        ///㐣,fu,fu,fu
        ///㐤,da [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string yue {
            get {
                return ResourceManager.GetString("yue", resourceCulture);
            }
        }
    }
}
