cmake_minimum_required(VERSION 3.24)

foreach(required OPUM_RID OPUM_BUILD_ROOT OPUM_INSTALL_ROOT)
    if(NOT ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()

set(source "${CMAKE_CURRENT_LIST_DIR}")
set(build "${OPUM_BUILD_ROOT}/${OPUM_RID}")
set(destination "${OPUM_INSTALL_ROOT}/${OPUM_RID}")
set(arguments -DCMAKE_BUILD_TYPE=Release)

if(OPUM_RID MATCHES "^android-")
    if(NOT OPUM_ANDROID_SDK)
        set(OPUM_ANDROID_SDK "$ENV{ANDROID_HOME}")
    endif()
    if(NOT OPUM_ANDROID_SDK)
        set(OPUM_ANDROID_SDK "$ENV{ANDROID_SDK_ROOT}")
    endif()
    if(NOT OPUM_ANDROID_SDK AND CMAKE_HOST_WIN32)
        set(OPUM_ANDROID_SDK "$ENV{LOCALAPPDATA}/Android/Sdk")
    elseif(NOT OPUM_ANDROID_SDK AND CMAKE_HOST_APPLE)
        set(OPUM_ANDROID_SDK "$ENV{HOME}/Library/Android/sdk")
    elseif(NOT OPUM_ANDROID_SDK)
        set(OPUM_ANDROID_SDK "$ENV{HOME}/Android/Sdk")
    endif()
    file(READ "${source}/android-ndk-version.txt" ndk_version)
    string(STRIP "${ndk_version}" ndk_version)
    if(NOT OPUM_ANDROID_NDK)
        set(OPUM_ANDROID_NDK "${OPUM_ANDROID_SDK}/ndk/${ndk_version}")
    endif()
    file(TO_CMAKE_PATH "${OPUM_ANDROID_NDK}" OPUM_ANDROID_NDK)
    set(toolchain "${OPUM_ANDROID_NDK}/build/cmake/android.toolchain.cmake")
    if(NOT EXISTS "${toolchain}")
        message(FATAL_ERROR "Android NDK toolchain not found: ${toolchain}. Set AndroidNdkDirectory in MSBuild (OPUM_ANDROID_NDK for this script), or install the default NDK with sdkmanager \"ndk;${ndk_version}\" under your Android SDK.")
    endif()
    if(OPUM_RID STREQUAL "android-arm64")
        set(abi arm64-v8a)
    elseif(OPUM_RID STREQUAL "android-arm")
        set(abi armeabi-v7a)
    elseif(OPUM_RID STREQUAL "android-x64")
        set(abi x86_64)
    elseif(OPUM_RID STREQUAL "android-x86")
        set(abi x86)
    else()
        message(FATAL_ERROR "Unsupported Android RID: ${OPUM_RID}")
    endif()
    list(APPEND arguments "-DCMAKE_TOOLCHAIN_FILE=${toolchain}" "-DANDROID_ABI=${abi}"
        -DANDROID_PLATFORM=android-24 -DANDROID_STL=c++_static -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON)
    set(OPUM_GENERATOR Ninja)
elseif(OPUM_RID MATCHES "^win-" AND CMAKE_HOST_WIN32)
    # 优先使用注册的 Visual Studio；便携 MinGW 环境也可直接进行本机调试。
    if(NOT OPUM_GENERATOR AND NOT EXISTS "${build}/CMakeCache.txt")
        set(program_files_x86 "ProgramFiles(x86)")
        find_program(vswhere vswhere.exe PATHS "$ENV{${program_files_x86}}/Microsoft Visual Studio/Installer")
        if(OPUM_RID STREQUAL "win-arm64")
            set(vc_component Microsoft.VisualStudio.Component.VC.Tools.ARM64)
        else()
            set(vc_component Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
        endif()
        if(vswhere)
            execute_process(COMMAND "${vswhere}" -latest -products * -requires "${vc_component}" -property installationPath
                OUTPUT_VARIABLE visual_studio OUTPUT_STRIP_TRAILING_WHITESPACE)
        endif()
        if(NOT visual_studio)
            find_program(cxx cl)
            if(cxx)
                set(OPUM_GENERATOR "NMake Makefiles")
            else()
                find_program(mingw_make mingw32-make)
                if(mingw_make)
                    set(OPUM_GENERATOR "MinGW Makefiles")
                else()
                    message(FATAL_ERROR "Install Visual Studio C++ Build Tools (including Windows SDK), or use a configured C++ developer terminal. See native/game/README.md.")
                endif()
            endif()
        endif()
    endif()
    if((NOT OPUM_GENERATOR AND NOT EXISTS "${build}/CMakeCache.txt") OR OPUM_GENERATOR MATCHES "Visual Studio")
        if(OPUM_RID STREQUAL "win-arm64")
            list(APPEND arguments -A ARM64)
        elseif(OPUM_RID STREQUAL "win-x86")
            list(APPEND arguments -A Win32)
        else()
            list(APPEND arguments -A x64)
        endif()
    endif()
elseif(OPUM_RID MATCHES "^osx-" AND CMAKE_HOST_APPLE)
    if(OPUM_RID STREQUAL "osx-arm64")
        list(APPEND arguments -DCMAKE_OSX_ARCHITECTURES=arm64)
    else()
        list(APPEND arguments -DCMAKE_OSX_ARCHITECTURES=x86_64)
    endif()
elseif(NOT (OPUM_RID MATCHES "^linux-" AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux"))
    message(FATAL_ERROR "Cannot build ${OPUM_RID} on ${CMAKE_HOST_SYSTEM_NAME} without a matching toolchain.")
endif()

if(OPUM_GENERATOR)
    list(APPEND arguments -G "${OPUM_GENERATOR}")
endif()
# 每次交给 CMake 检查源码增量；不依赖旧 DLL 的存在与否判断是否需要编译。
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${build}"
    "-DOPUM_RID=${OPUM_RID}" ${arguments} COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --config Release --target opum_game --parallel 2
    COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${build}" --config Release --component GameRuntime --prefix "${destination}"
    COMMAND_ERROR_IS_FATAL ANY)
