<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <DefineConstants>LINUX</DefineConstants>
        <RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu.Linux" Version="1.29.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OpenUtauMobile\OpenUtauMobile.csproj"/>
    </ItemGroup>
    <Import Project="../native/DesktopNative.targets" />
    <Import Project="../native/game/GameNative.targets" />
</Project>

